/**:
    ros__parameters:
      video_device: "/dev/v4l/by-id/usb-Sunplus_IT_Co_Trust_USB_Camera_20200415001-video-index0"
      framerate: 12.0
      io_method: "mmap"
      frame_id: "logitech_c920_right_link"
      pixel_format: "mjpeg2rgb"
      av_device_format: "YUV422P"
      image_width: 1280
      image_height: 720
      camera_name: "right_camera"
      camera_info_url: "package://robot_localization_monitor/config/camera_info_2.yaml"
      brightness: -1
      contrast: -1
      saturation: -1
      sharpness: -1
      gain: -1
      auto_white_balance: true
      white_balance: 4000
      autoexposure: true
      exposure: 100
      autofocus: false
      focus: -1
