/**:
    ros__parameters:
      video_device: "/dev/video2"
      framerate: 12.0
      io_method: "mmap"
      frame_id: "logitech_c920_back_link"
      pixel_format: "mjpeg2rgb"
      av_device_format: "YUV422P"
      image_width: 1280
      image_height: 720
      camera_name: "back_camera"
      camera_info_url: "package://usb_cam/config/camera_info.yaml"
      brightness: -1
      contrast: -1
      saturation: -1
      sharpness: -1
      gain: -1
      auto_white_balance: true
      white_balance: 4000
      autoexposure: true
      exposure: 100
      autofocus: false
      focus: -1
