site_name: MoMo Documentation
site_url: https://tuhh-itl.github.io/MoMo/

repo_name: MoMo
repo_url: https://github.com/TUHH-ITL/MoMo

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  icon: 
    repo: fontawesome/brands/github
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime
  favicon: assets/favicon.png
  logo: assets/favicon.png

plugins:
  - social
  - search

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/TUHH-ITL      
    - icon: fontawesome/brands/instagram            
      link: https://www.instagram.com/itlhamburg/
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/school/institut-fuer-technische-logistik-tuhh/mycompany/
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCjfr0QytTA29dJInXSUQz8w
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

copyright: |
  &copy; 2024 <a href="https://www3.tuhh.de/itl/"  target="_blank" rel="noopener">Institut für Technische Logistik</a>
  
